# ?  \u5339\u914D\u4EFB\u4F55\u5355\u5B57\u7B26
# *  \u5339\u914D0\u6216\u8005\u4EFB\u610F\u6570\u91CF\u7684\u5B57\u7B26
# ** \u5339\u914D0\u6216\u8005\u66F4\u591A\u7684\u76EE\u5F55
path_1=/control/**
path_2=/admin/**
path_3=/column/**
path_4=/user
path_5=/user/control/**
path_6=/install
path_7=/more/**
path_8=/backstage/**
path_9=/common/**
path_10=/file/**
path_11=/captcha/**
path_12=/checkCaptcha
path_17=/userVerification
path_18=/logout
path_19=/keepSessionAlive
path_20=/robots
path_21=/feedback/control/**
path_22=/error/**
path_23=/notify/**
path_24=/paymentCompleted/**
path_25=/fileDownload

path_90=/statistic/**
path_100=/favicon
path_200=/media/**
path_300=/thirdParty/**

path_400=/smsCode
path_500=/baseInfo
path_600=/api/**